// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMuO6-z5lTyVQ6DtQCtwoCmYze-rXwHzA',
    appId: '1:57764613082:web:7cdba53d1b0aef2fc5cee3',
    messagingSenderId: '57764613082',
    projectId: 'juancarlo-e80bf',
    authDomain: 'juancarlo-e80bf.firebaseapp.com',
    storageBucket: 'juancarlo-e80bf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeE8uFcFBQfYwu0NLHp9nYR8l5O1H2aGw',
    appId: '1:57764613082:android:bfe57b236e8ccc90c5cee3',
    messagingSenderId: '57764613082',
    projectId: 'juancarlo-e80bf',
    storageBucket: 'juancarlo-e80bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzS4sXgAtwa5SUeF8Ir7IvBz_9wgIYl8Y',
    appId: '1:57764613082:ios:cf1e97445c812f0cc5cee3',
    messagingSenderId: '57764613082',
    projectId: 'juancarlo-e80bf',
    storageBucket: 'juancarlo-e80bf.firebasestorage.app',
    iosBundleId: 'com.example.eventRegistration',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzS4sXgAtwa5SUeF8Ir7IvBz_9wgIYl8Y',
    appId: '1:57764613082:ios:cf1e97445c812f0cc5cee3',
    messagingSenderId: '57764613082',
    projectId: 'juancarlo-e80bf',
    storageBucket: 'juancarlo-e80bf.firebasestorage.app',
    iosBundleId: 'com.example.eventRegistration',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMuO6-z5lTyVQ6DtQCtwoCmYze-rXwHzA',
    appId: '1:57764613082:web:569853c00165c539c5cee3',
    messagingSenderId: '57764613082',
    projectId: 'juancarlo-e80bf',
    authDomain: 'juancarlo-e80bf.firebaseapp.com',
    storageBucket: 'juancarlo-e80bf.firebasestorage.app',
  );

}